{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64980,
          "sha512": "688ba43d34f9e3ccabb02e0af163f275a3f60740b0d11a9d496ba7c68aae05a7288321ce6a16a4584031b898214b2d98b03acd783467de1c337bc2820a5e6f3e",
          "sha256": "92d1c1f289d7679d5dccfce2bdfb3f2bed5977081d626751d575bbee668e44f1",
          "sha1": "485e201f2a20cada49a1ed681db4f9bb40c2e8d6",
          "md5": "0f848d258c95484c018101e3eedbe029"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64980,
          "sha512": "688ba43d34f9e3ccabb02e0af163f275a3f60740b0d11a9d496ba7c68aae05a7288321ce6a16a4584031b898214b2d98b03acd783467de1c337bc2820a5e6f3e",
          "sha256": "92d1c1f289d7679d5dccfce2bdfb3f2bed5977081d626751d575bbee668e44f1",
          "sha1": "485e201f2a20cada49a1ed681db4f9bb40c2e8d6",
          "md5": "0f848d258c95484c018101e3eedbe029"
        }
      ]
    }
  ]
}
