{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 12659,
          "sha512": "965e9a821b2017c53e44a5f67a2d9b3d04195ef9049bc8cb55a928a6d76909f2cd18deb46ce033a2cbe132996408bbb5dfb1560f864c5acd107893186784134e",
          "sha256": "1b0c4c760b7cf49e13bc6257083dbcf0b53f4b8c3777649d906ae89141433096",
          "sha1": "e8c52bf254fef1c46fb1f70ffe2108d2e7243812",
          "md5": "2eed78591c8602bcf7e0457d52716afe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 12659,
          "sha512": "965e9a821b2017c53e44a5f67a2d9b3d04195ef9049bc8cb55a928a6d76909f2cd18deb46ce033a2cbe132996408bbb5dfb1560f864c5acd107893186784134e",
          "sha256": "1b0c4c760b7cf49e13bc6257083dbcf0b53f4b8c3777649d906ae89141433096",
          "sha1": "e8c52bf254fef1c46fb1f70ffe2108d2e7243812",
          "md5": "2eed78591c8602bcf7e0457d52716afe"
        }
      ]
    }
  ]
}
