{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64748,
          "sha512": "5d925cc528335103cb2191c3c3ace0e74588739579df87a9ab2c45142f8cb5477554f8fe368ebf24604de9dbfcf916e7d2ac6283a8e712d0074405a0e7f359ea",
          "sha256": "2c3303a44d559c0e22501efeb14dbb5ea5a692025133a748e6d950f5d4a50a31",
          "sha1": "60e4be8f41d3402d604f74104e3c97cf8a63e274",
          "md5": "b7dfc118d00f0d2542a2bcb894677a96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64748,
          "sha512": "5d925cc528335103cb2191c3c3ace0e74588739579df87a9ab2c45142f8cb5477554f8fe368ebf24604de9dbfcf916e7d2ac6283a8e712d0074405a0e7f359ea",
          "sha256": "2c3303a44d559c0e22501efeb14dbb5ea5a692025133a748e6d950f5d4a50a31",
          "sha1": "60e4be8f41d3402d604f74104e3c97cf8a63e274",
          "md5": "b7dfc118d00f0d2542a2bcb894677a96"
        }
      ]
    }
  ]
}
