{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61413,
          "sha512": "35104386d7cd0198f101fcaee6dae84bcd54a45596877317e19ab156f60b353737f3e0704e5b568b32e9d03674c5ad09b1fb7550f711000fb64faba9f1a42fa3",
          "sha256": "3a0ea0570680e50b08f568ebc0aa74a815f526360e534a3171dc5709134885e8",
          "sha1": "c8d279d3c41142023873c4f8e660e39f54c20e84",
          "md5": "67246464c9924f4cbab8dc4134ffaa0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61413,
          "sha512": "35104386d7cd0198f101fcaee6dae84bcd54a45596877317e19ab156f60b353737f3e0704e5b568b32e9d03674c5ad09b1fb7550f711000fb64faba9f1a42fa3",
          "sha256": "3a0ea0570680e50b08f568ebc0aa74a815f526360e534a3171dc5709134885e8",
          "sha1": "c8d279d3c41142023873c4f8e660e39f54c20e84",
          "md5": "67246464c9924f4cbab8dc4134ffaa0d"
        }
      ]
    }
  ]
}
