{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59911,
          "sha512": "1b1b578dc52df3922027ee6f38a0a3f41f73c9173751ba371de8be98537b6e681ff5c816ae56bd6956f86c3c0b2ea474ee4162d544d86dcf14d4ce1e009ca3ab",
          "sha256": "eddcc4a69ce2428b7b9e743d3c1a6bbc168850141211ba38a8b782fd724d1eb8",
          "sha1": "291927beeac41ba7108608ca719fed6b4993b313",
          "md5": "bc8938f7695ae4720c22a5407f871169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59911,
          "sha512": "1b1b578dc52df3922027ee6f38a0a3f41f73c9173751ba371de8be98537b6e681ff5c816ae56bd6956f86c3c0b2ea474ee4162d544d86dcf14d4ce1e009ca3ab",
          "sha256": "eddcc4a69ce2428b7b9e743d3c1a6bbc168850141211ba38a8b782fd724d1eb8",
          "sha1": "291927beeac41ba7108608ca719fed6b4993b313",
          "md5": "bc8938f7695ae4720c22a5407f871169"
        }
      ]
    }
  ]
}
