{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65010,
          "sha512": "5545cfa58753bae819fe6ba0d90f0bf95de8a02537d60fe1d9cbe76031b3b9722b0f95587d78662639bf30b714e44bb7567b3f17c981c03e5582445163fabf30",
          "sha256": "5477825de6a66036791a4f967c558df1f68abea73d3b561a1bb915497dbf5461",
          "sha1": "77be320e8d0d77834cf7e7f96d34f679671154a8",
          "md5": "5732c0b955de14ddfa5aa1c36a13dcc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65010,
          "sha512": "5545cfa58753bae819fe6ba0d90f0bf95de8a02537d60fe1d9cbe76031b3b9722b0f95587d78662639bf30b714e44bb7567b3f17c981c03e5582445163fabf30",
          "sha256": "5477825de6a66036791a4f967c558df1f68abea73d3b561a1bb915497dbf5461",
          "sha1": "77be320e8d0d77834cf7e7f96d34f679671154a8",
          "md5": "5732c0b955de14ddfa5aa1c36a13dcc8"
        }
      ]
    }
  ]
}
