{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56633,
          "sha512": "f0f187a025adc7349d9d1fd7b82983f638c22ee3361caa5f617ebb0ed79ef66a6f90ceeb6be7e09989c2113ec9134eb076907af2d9298c522524ccc562fe405c",
          "sha256": "925dcebff2d9df1df8a23eea0488d8dd9c1a041a3b2cebc63cfb70b48949ab8a",
          "sha1": "d1b05b55dd9f7319883d3bb97926ef5aa2382ad4",
          "md5": "29ae35805a45b70af47b43f77e1b4440"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56633,
          "sha512": "f0f187a025adc7349d9d1fd7b82983f638c22ee3361caa5f617ebb0ed79ef66a6f90ceeb6be7e09989c2113ec9134eb076907af2d9298c522524ccc562fe405c",
          "sha256": "925dcebff2d9df1df8a23eea0488d8dd9c1a041a3b2cebc63cfb70b48949ab8a",
          "sha1": "d1b05b55dd9f7319883d3bb97926ef5aa2382ad4",
          "md5": "29ae35805a45b70af47b43f77e1b4440"
        }
      ]
    }
  ]
}
