{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25066,
          "sha512": "c7410e140cb16870b1a5c9afe768df8ff4ef99355c3e7c7a496e3d8bafd0b040b09d1b219b9836337a66d1931a47156ba08f136af161a03e348d3bdb6a02e875",
          "sha256": "ab9fb209aa69abbcbdd901eeb187e440555b32bc2903989ee3bc5472f5975f8f",
          "sha1": "36bc4f0d6bd7871a631e68b08d8314e0eaf37535",
          "md5": "8fc174bbac64808169be6be82ac8cc1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25066,
          "sha512": "c7410e140cb16870b1a5c9afe768df8ff4ef99355c3e7c7a496e3d8bafd0b040b09d1b219b9836337a66d1931a47156ba08f136af161a03e348d3bdb6a02e875",
          "sha256": "ab9fb209aa69abbcbdd901eeb187e440555b32bc2903989ee3bc5472f5975f8f",
          "sha1": "36bc4f0d6bd7871a631e68b08d8314e0eaf37535",
          "md5": "8fc174bbac64808169be6be82ac8cc1a"
        }
      ]
    }
  ]
}
