{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21813,
          "sha512": "bf5a7f782589760f63fa906a203a4e6f7928d4f7c5832cc641cf289263270e88d5d7e8a5f166af75e948119cc39b35c9485a4356389d3ab895cc432d9c0e003c",
          "sha256": "9834f14823bd63603bced5f410a937105150095995f44fb33ca26b1285bc4c51",
          "sha1": "763ecf207665ed6413f5d20502339f3f1f34a241",
          "md5": "704fbbb5da21e05d0ebc5e6e9ec47e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21813,
          "sha512": "bf5a7f782589760f63fa906a203a4e6f7928d4f7c5832cc641cf289263270e88d5d7e8a5f166af75e948119cc39b35c9485a4356389d3ab895cc432d9c0e003c",
          "sha256": "9834f14823bd63603bced5f410a937105150095995f44fb33ca26b1285bc4c51",
          "sha1": "763ecf207665ed6413f5d20502339f3f1f34a241",
          "md5": "704fbbb5da21e05d0ebc5e6e9ec47e79"
        }
      ]
    }
  ]
}
