{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61412,
          "sha512": "0e4225e7c2fad64f840310f360192386777c6944690e5fa15db0d8e533d0ded0b76d692eb4469e6b40ece6430cdf4496829ab5de3a35386cb0c28598390e17e2",
          "sha256": "763adc5a22171c90064af30556f5a6d6898ff7b0332dfc3df364537bd32e3f4b",
          "sha1": "9657815c9104565f6551d520fbb2709534ac95db",
          "md5": "b088dfd55504a0a17922296526e18f65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61412,
          "sha512": "0e4225e7c2fad64f840310f360192386777c6944690e5fa15db0d8e533d0ded0b76d692eb4469e6b40ece6430cdf4496829ab5de3a35386cb0c28598390e17e2",
          "sha256": "763adc5a22171c90064af30556f5a6d6898ff7b0332dfc3df364537bd32e3f4b",
          "sha1": "9657815c9104565f6551d520fbb2709534ac95db",
          "md5": "b088dfd55504a0a17922296526e18f65"
        }
      ]
    }
  ]
}
