{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56844,
          "sha512": "e6357c3418580431924de873714e78ef61b2b9003d7c2b19f24f8edcd91690fc59f92cd4b9271d0176903f6d730f60107a2289a4fb3cf412073e37d13b2efa07",
          "sha256": "caede0f1001f9694e9783d3fbd7ebd69b89e017bf25265af5c92e9d664d4dd02",
          "sha1": "23db2cfe8255b42a009ef1c51c60050dad7f8707",
          "md5": "e0dc032847b08f2d95cef833d624fddd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56844,
          "sha512": "e6357c3418580431924de873714e78ef61b2b9003d7c2b19f24f8edcd91690fc59f92cd4b9271d0176903f6d730f60107a2289a4fb3cf412073e37d13b2efa07",
          "sha256": "caede0f1001f9694e9783d3fbd7ebd69b89e017bf25265af5c92e9d664d4dd02",
          "sha1": "23db2cfe8255b42a009ef1c51c60050dad7f8707",
          "md5": "e0dc032847b08f2d95cef833d624fddd"
        }
      ]
    }
  ]
}
