{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 4712,
          "sha512": "0b24f717167d0c47cdc0a872ac142d9aa689e34c259f9897dab0f66dc28e540b04d9202affc62e1743664f0739bf4b70a0e2aa595fcab095b97a4b1a49a16b10",
          "sha256": "d2fd0dc6e561b1c70144ee6a54fce6ad6af45b45d944365353aee45d677a3e25",
          "sha1": "0133187a04559a78a938f7cab1e7e7faa8428bac",
          "md5": "061f118f3ad15349f1138882e0ac3375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 4712,
          "sha512": "0b24f717167d0c47cdc0a872ac142d9aa689e34c259f9897dab0f66dc28e540b04d9202affc62e1743664f0739bf4b70a0e2aa595fcab095b97a4b1a49a16b10",
          "sha256": "d2fd0dc6e561b1c70144ee6a54fce6ad6af45b45d944365353aee45d677a3e25",
          "sha1": "0133187a04559a78a938f7cab1e7e7faa8428bac",
          "md5": "061f118f3ad15349f1138882e0ac3375"
        }
      ]
    }
  ]
}
