{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65809,
          "sha512": "f9a2c51b1243fba2a57d07ff4cf90d9e2392bda3e9eb0471c860e9a3d51ae4b13cd2a9798d1d781b996fa6cc5631fb78db3ae8acfc34da254a4c0fe538991ae9",
          "sha256": "deb97a932e5adf0327cfd43b4b3bca5adf5b7f4eba5e98951d379cfdd8c58e18",
          "sha1": "9d598bee1539a522ab631cbbd1ddc665ce245001",
          "md5": "2d3c0680860c82e8d793abe596a6f3c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65809,
          "sha512": "f9a2c51b1243fba2a57d07ff4cf90d9e2392bda3e9eb0471c860e9a3d51ae4b13cd2a9798d1d781b996fa6cc5631fb78db3ae8acfc34da254a4c0fe538991ae9",
          "sha256": "deb97a932e5adf0327cfd43b4b3bca5adf5b7f4eba5e98951d379cfdd8c58e18",
          "sha1": "9d598bee1539a522ab631cbbd1ddc665ce245001",
          "md5": "2d3c0680860c82e8d793abe596a6f3c7"
        }
      ]
    }
  ]
}
