{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 29049,
          "sha512": "d86bd5119aaa7b87a63ba0f0588b6d8b33f15069c6c50d4de5d5e21a76c46b7075609a119833d989441aa845a862ddbfcc2c6ef6bf29a95483c64e82ed7d0236",
          "sha256": "6053f86f4b2486b059b696244ebe6c507f27c7219080f9b989b1e5229d071626",
          "sha1": "0b4a0659e317ac9fff2a78de12e1a10c7a097284",
          "md5": "75cb7b6cc62df0b66f80038d22394914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 29049,
          "sha512": "d86bd5119aaa7b87a63ba0f0588b6d8b33f15069c6c50d4de5d5e21a76c46b7075609a119833d989441aa845a862ddbfcc2c6ef6bf29a95483c64e82ed7d0236",
          "sha256": "6053f86f4b2486b059b696244ebe6c507f27c7219080f9b989b1e5229d071626",
          "sha1": "0b4a0659e317ac9fff2a78de12e1a10c7a097284",
          "md5": "75cb7b6cc62df0b66f80038d22394914"
        }
      ]
    }
  ]
}
