{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65088,
          "sha512": "612b731e8b29c959fd284df64e822cba9b4fdaa82728645d8c7457ce19b3baaae76921fb44d5eb4648e3f30b70ac8731463b080a2e2cadc199e01f77f2181c1a",
          "sha256": "4400c305b5751af7dec092fadbbe966e48bf2a0a3f304f42b920549433e8bd46",
          "sha1": "39d4dc2380273ea67a9c001cc90143316420d54f",
          "md5": "78c3fff4a9a89971e04514914f93f0ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65088,
          "sha512": "612b731e8b29c959fd284df64e822cba9b4fdaa82728645d8c7457ce19b3baaae76921fb44d5eb4648e3f30b70ac8731463b080a2e2cadc199e01f77f2181c1a",
          "sha256": "4400c305b5751af7dec092fadbbe966e48bf2a0a3f304f42b920549433e8bd46",
          "sha1": "39d4dc2380273ea67a9c001cc90143316420d54f",
          "md5": "78c3fff4a9a89971e04514914f93f0ce"
        }
      ]
    }
  ]
}
