{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56943,
          "sha512": "4d7be321bf9aaf4b40359d0c7c4b5f0e0e2bf6557abd1347778f030ec60d648a7fa7a29d425dc435db1b1dbb42c87b83a6a0c96e592391b3c2309616137f84bc",
          "sha256": "05561787bb9e58df2c5c0809229af65a25af26f27d06a92f2a0694a3f5859af4",
          "sha1": "db61b3bd58d97d202bd7e32cce5eee78d90eaaae",
          "md5": "eca63b2fdc22bbaad6d6c96588b4fee5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56943,
          "sha512": "4d7be321bf9aaf4b40359d0c7c4b5f0e0e2bf6557abd1347778f030ec60d648a7fa7a29d425dc435db1b1dbb42c87b83a6a0c96e592391b3c2309616137f84bc",
          "sha256": "05561787bb9e58df2c5c0809229af65a25af26f27d06a92f2a0694a3f5859af4",
          "sha1": "db61b3bd58d97d202bd7e32cce5eee78d90eaaae",
          "md5": "eca63b2fdc22bbaad6d6c96588b4fee5"
        }
      ]
    }
  ]
}
