{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56352,
          "sha512": "78d3e672d46ae5722614bb4b824b56249a4a5dea6e72e03e69e823d1d404640f17ba1685457b101ac0b6fc864c41b3103ba0de3b15bbb6eb092c483bba62e30a",
          "sha256": "b4c77dd4fbb90706b9e6cb159a62a6dfc570d3dd4f60384b8c52bffb9111bbf5",
          "sha1": "5c5c0aa9af658aa3a329a363e182bd8b1541048f",
          "md5": "5bb88c05d85cfc0b76a486d53e415037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56352,
          "sha512": "78d3e672d46ae5722614bb4b824b56249a4a5dea6e72e03e69e823d1d404640f17ba1685457b101ac0b6fc864c41b3103ba0de3b15bbb6eb092c483bba62e30a",
          "sha256": "b4c77dd4fbb90706b9e6cb159a62a6dfc570d3dd4f60384b8c52bffb9111bbf5",
          "sha1": "5c5c0aa9af658aa3a329a363e182bd8b1541048f",
          "md5": "5bb88c05d85cfc0b76a486d53e415037"
        }
      ]
    }
  ]
}
