{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21889,
          "sha512": "ecf81cd9b531c29329fb693cb73a106da9049330e6b4f2ce96a18c197876370a5a4fe4b47c742bb695d2e3f84d520d83e5a3aaef9b840697bc4d68dfe9b39222",
          "sha256": "5147cb76f1a2a00497e5220b453b7a19b52a0b2a2a75be11a73ff233c9cfb97e",
          "sha1": "2d1a6b7776b27dbd541624c3221b6769293b26a5",
          "md5": "517da5af7264f0cca65318f7d0426b56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21889,
          "sha512": "ecf81cd9b531c29329fb693cb73a106da9049330e6b4f2ce96a18c197876370a5a4fe4b47c742bb695d2e3f84d520d83e5a3aaef9b840697bc4d68dfe9b39222",
          "sha256": "5147cb76f1a2a00497e5220b453b7a19b52a0b2a2a75be11a73ff233c9cfb97e",
          "sha1": "2d1a6b7776b27dbd541624c3221b6769293b26a5",
          "md5": "517da5af7264f0cca65318f7d0426b56"
        }
      ]
    }
  ]
}
