{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64996,
          "sha512": "81513d1b0f9ad2da8f36b917ece8c8b5683f163f9d65f6fb213c8c00b62625005f3eda6fcfd7897d9f6dcde7ef85243908e062e21b9b2c994d5414ce93a3c1fa",
          "sha256": "35da39a1e5e721fa4fe13612d87d98311c4f09f166b81cfb9a7dd71c29b3f624",
          "sha1": "083ede6c18c64c8bb031cc33d885c8299524436c",
          "md5": "9960fe1d1ffcf21294fc1c04a12b1e77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64996,
          "sha512": "81513d1b0f9ad2da8f36b917ece8c8b5683f163f9d65f6fb213c8c00b62625005f3eda6fcfd7897d9f6dcde7ef85243908e062e21b9b2c994d5414ce93a3c1fa",
          "sha256": "35da39a1e5e721fa4fe13612d87d98311c4f09f166b81cfb9a7dd71c29b3f624",
          "sha1": "083ede6c18c64c8bb031cc33d885c8299524436c",
          "md5": "9960fe1d1ffcf21294fc1c04a12b1e77"
        }
      ]
    }
  ]
}
