{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59912,
          "sha512": "43a94833d4464f0bc7cd5981adf024b1b92b45b95806eeb3e8e54154e49c9baa46f9f295b6d807bb2e35b3897456c950b404bba292d8adc90398692136ca852b",
          "sha256": "5df26776cf3c8eeee575e93914f8e34bf698bac8e30ca8b050f139b76c31e153",
          "sha1": "91e692ec3925076c630f51efb83eeb9bb181561a",
          "md5": "8120419a1b80cee7275dedc9edb8acb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59912,
          "sha512": "43a94833d4464f0bc7cd5981adf024b1b92b45b95806eeb3e8e54154e49c9baa46f9f295b6d807bb2e35b3897456c950b404bba292d8adc90398692136ca852b",
          "sha256": "5df26776cf3c8eeee575e93914f8e34bf698bac8e30ca8b050f139b76c31e153",
          "sha1": "91e692ec3925076c630f51efb83eeb9bb181561a",
          "md5": "8120419a1b80cee7275dedc9edb8acb1"
        }
      ]
    }
  ]
}
