{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65456,
          "sha512": "e0b1bad5ec8099a05e42f2dc6cc3a452460eae9d92fbeffaf4df1f7aabab3dacd37f4d0777ad1fdf849ab81bb4ff92378843e5b569cd91439bb7ac6814c826f8",
          "sha256": "993bc2ce48ccd5faacb4fc62ad0c3d77917937fb9a03da9b61e22ff52b564960",
          "sha1": "82800c4cea23717ecdf7b22832df3119ef825d3a",
          "md5": "f2b0e549a6bca87b18e0f5e825c5f847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65456,
          "sha512": "e0b1bad5ec8099a05e42f2dc6cc3a452460eae9d92fbeffaf4df1f7aabab3dacd37f4d0777ad1fdf849ab81bb4ff92378843e5b569cd91439bb7ac6814c826f8",
          "sha256": "993bc2ce48ccd5faacb4fc62ad0c3d77917937fb9a03da9b61e22ff52b564960",
          "sha1": "82800c4cea23717ecdf7b22832df3119ef825d3a",
          "md5": "f2b0e549a6bca87b18e0f5e825c5f847"
        }
      ]
    }
  ]
}
