{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59925,
          "sha512": "fee7e10e0c2da59ad76a1c75eea43fda1b06c648251bc844642d2cdb18004ecfefb6e7e9a9612ca07ab4830dc81e11421052032bf6d246d5663806ca6083eadd",
          "sha256": "fb95bd7b2c8267b205a92fba25fdf5f2c96a063d7cb5671404c839b6c5a91b71",
          "sha1": "8c8f4fffc2f633313478c152cf111336d9daf9d2",
          "md5": "3ee96be6ba6631500e12350e986b24c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59925,
          "sha512": "fee7e10e0c2da59ad76a1c75eea43fda1b06c648251bc844642d2cdb18004ecfefb6e7e9a9612ca07ab4830dc81e11421052032bf6d246d5663806ca6083eadd",
          "sha256": "fb95bd7b2c8267b205a92fba25fdf5f2c96a063d7cb5671404c839b6c5a91b71",
          "sha1": "8c8f4fffc2f633313478c152cf111336d9daf9d2",
          "md5": "3ee96be6ba6631500e12350e986b24c8"
        }
      ]
    }
  ]
}
