{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61426,
          "sha512": "4c1a5422f70354ae4c7115d5a4fa4be446cd59d0ad401315c87e4625d2fd61f0df125600e5823f77e207ac6451bc7baf5ce3df4e40f1ce1adffa441d38cfa733",
          "sha256": "7304b7707f03f4756732633643fd440dbc35b32e4db833e72e4cf64f12e2d07a",
          "sha1": "4793dcf570a8ca7d93aaa0df6d8eaf041d0849cb",
          "md5": "196df82140e293d15f650a5226e57098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61426,
          "sha512": "4c1a5422f70354ae4c7115d5a4fa4be446cd59d0ad401315c87e4625d2fd61f0df125600e5823f77e207ac6451bc7baf5ce3df4e40f1ce1adffa441d38cfa733",
          "sha256": "7304b7707f03f4756732633643fd440dbc35b32e4db833e72e4cf64f12e2d07a",
          "sha1": "4793dcf570a8ca7d93aaa0df6d8eaf041d0849cb",
          "md5": "196df82140e293d15f650a5226e57098"
        }
      ]
    }
  ]
}
