{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64701,
          "sha512": "cd4721387e31f4bacff18a574b8daae067c70ef251a2fa3856a1079496d57106abeaef026ffb823a61b80acdc304a60fcd5460dd5e8ee8852b73e3071588a2ae",
          "sha256": "c5daee0ad181621a6872ccf2b232fcd5724e692dc2e952f213bf0d764984555c",
          "sha1": "4552a5a7dab740c850f47ff622173b38868601cb",
          "md5": "db3eba157c2b122ee5f1a185e457ee61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64701,
          "sha512": "cd4721387e31f4bacff18a574b8daae067c70ef251a2fa3856a1079496d57106abeaef026ffb823a61b80acdc304a60fcd5460dd5e8ee8852b73e3071588a2ae",
          "sha256": "c5daee0ad181621a6872ccf2b232fcd5724e692dc2e952f213bf0d764984555c",
          "sha1": "4552a5a7dab740c850f47ff622173b38868601cb",
          "md5": "db3eba157c2b122ee5f1a185e457ee61"
        }
      ]
    }
  ]
}
