{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53775,
          "sha512": "f094b304ba40bb8bac3c57fd89a0cda19c71e695f73e6a99ea338bf67c866ac6433929f89468f7362caa5fb70e7151d603a499cf368ea7666e699f2d87917603",
          "sha256": "fdfa14db9513fd4370dc566920413a13040443082bf2aa2f99497460cccaa2ac",
          "sha1": "cd3c25cc09f2c1ce4dbe488d8e1441731916ab74",
          "md5": "de0968317c213aad6ae0a20702c569a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53775,
          "sha512": "f094b304ba40bb8bac3c57fd89a0cda19c71e695f73e6a99ea338bf67c866ac6433929f89468f7362caa5fb70e7151d603a499cf368ea7666e699f2d87917603",
          "sha256": "fdfa14db9513fd4370dc566920413a13040443082bf2aa2f99497460cccaa2ac",
          "sha1": "cd3c25cc09f2c1ce4dbe488d8e1441731916ab74",
          "md5": "de0968317c213aad6ae0a20702c569a7"
        }
      ]
    }
  ]
}
