{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21818,
          "sha512": "4857ffcac67ff0dcf853348a5cadaec549b20c44b2bb83a6425da01693516663a41cff988444f709312ef95e7ada837d3cbb90afc389afde80d4a698ec3cb31f",
          "sha256": "9cc3776d56595bdc800b4534797159e9e3fcd5a4e13c65f893cbe411eff829ee",
          "sha1": "ea54f2e9df2ddc522e69d620168ce5a890978c68",
          "md5": "66db96f82d476a3fe41f2e283dc5363d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 21818,
          "sha512": "4857ffcac67ff0dcf853348a5cadaec549b20c44b2bb83a6425da01693516663a41cff988444f709312ef95e7ada837d3cbb90afc389afde80d4a698ec3cb31f",
          "sha256": "9cc3776d56595bdc800b4534797159e9e3fcd5a4e13c65f893cbe411eff829ee",
          "sha1": "ea54f2e9df2ddc522e69d620168ce5a890978c68",
          "md5": "66db96f82d476a3fe41f2e283dc5363d"
        }
      ]
    }
  ]
}
