{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55306,
          "sha512": "f854dea0f5dbd29e9149f99acf6283cc30ce8a6ef86ff1bc8adb41b302f88d1614263138edcc97ac395f5bd11800257526ceb118a222b27dd3d4d20ff0e17c05",
          "sha256": "24cbaa75acb736ba4d18a17416a7a2db09f0f4df939db074906734c32285be7d",
          "sha1": "2fc12f39a465d982c90f80117fa2e006843e1994",
          "md5": "1ce20c8f1a78b2b7230a68bc4025d73f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55306,
          "sha512": "f854dea0f5dbd29e9149f99acf6283cc30ce8a6ef86ff1bc8adb41b302f88d1614263138edcc97ac395f5bd11800257526ceb118a222b27dd3d4d20ff0e17c05",
          "sha256": "24cbaa75acb736ba4d18a17416a7a2db09f0f4df939db074906734c32285be7d",
          "sha1": "2fc12f39a465d982c90f80117fa2e006843e1994",
          "md5": "1ce20c8f1a78b2b7230a68bc4025d73f"
        }
      ]
    }
  ]
}
