{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 54655,
          "sha512": "40ed52dbf221a7b56f360ae820c6ce4fa94f502cf4460be78213456cb61c336bb71829164d798e317f3ac09a2b4826a7bc945b60ca5dbe5480f5c105dddac78b",
          "sha256": "8da65fde5b27e6c6ca38ce22ec14f69b366b7aa273ba130cd520ed95c0359d40",
          "sha1": "62b19e2715753a9f019a7dc859282d089ee4c9b1",
          "md5": "68f11da2ceb82561f44125520f0dddd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 54655,
          "sha512": "40ed52dbf221a7b56f360ae820c6ce4fa94f502cf4460be78213456cb61c336bb71829164d798e317f3ac09a2b4826a7bc945b60ca5dbe5480f5c105dddac78b",
          "sha256": "8da65fde5b27e6c6ca38ce22ec14f69b366b7aa273ba130cd520ed95c0359d40",
          "sha1": "62b19e2715753a9f019a7dc859282d089ee4c9b1",
          "md5": "68f11da2ceb82561f44125520f0dddd6"
        }
      ]
    }
  ]
}
