{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65813,
          "sha512": "ccba8fb30e0ce1ed060d762666d9783e6aaa873f259f2e9edb4b909eb23657338efa852177ba36b65aab59e6987da197dd04cf17cd6a7841408b40fcece194da",
          "sha256": "380b3c3d6b5745df4b3a1445cc0543831452c10a0b2508e30f1103696d89aea5",
          "sha1": "e6e24a47c8688bb967a6186cbbe80054cbcfa4e6",
          "md5": "725b2f7efa5f4c76e826520b999cfa94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65813,
          "sha512": "ccba8fb30e0ce1ed060d762666d9783e6aaa873f259f2e9edb4b909eb23657338efa852177ba36b65aab59e6987da197dd04cf17cd6a7841408b40fcece194da",
          "sha256": "380b3c3d6b5745df4b3a1445cc0543831452c10a0b2508e30f1103696d89aea5",
          "sha1": "e6e24a47c8688bb967a6186cbbe80054cbcfa4e6",
          "md5": "725b2f7efa5f4c76e826520b999cfa94"
        }
      ]
    }
  ]
}
