{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25597,
          "sha512": "4cf35af87ee783e07440dea5a3335db5d1ea209ed07628c958e0099845f7dd119ba129d8af6dd65893d5f19f0822549ac0bf2d150b7cc1cd2bba00835b54ac08",
          "sha256": "9a45afa6c23edce7207662cbe445c3680a59c05c4db9c69c7a6a6a45f939455d",
          "sha1": "d6669aca59e880c53b45b406357bb4a693fea945",
          "md5": "25525212ca9a1da4c981689c728bbaf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25597,
          "sha512": "4cf35af87ee783e07440dea5a3335db5d1ea209ed07628c958e0099845f7dd119ba129d8af6dd65893d5f19f0822549ac0bf2d150b7cc1cd2bba00835b54ac08",
          "sha256": "9a45afa6c23edce7207662cbe445c3680a59c05c4db9c69c7a6a6a45f939455d",
          "sha1": "d6669aca59e880c53b45b406357bb4a693fea945",
          "md5": "25525212ca9a1da4c981689c728bbaf9"
        }
      ]
    }
  ]
}
