{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53857,
          "sha512": "8f28f7a2a88b1dd0375fb342953dc741d0daf385bdaad6c1b09e21a97b0d1fd246f7c7126253073429ead91c0ade0b1cdb24ca9787e000f151e2729fc73017e1",
          "sha256": "9b272e46656fe3a8b0fb8451d2873acf8736e0a0811a99be62a558773cc2bfc2",
          "sha1": "0884c8548bea557a6f7a2c323b4ccc21a8d813f5",
          "md5": "2fe49b2ed412d40e7b09d18f56ffa1ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53857,
          "sha512": "8f28f7a2a88b1dd0375fb342953dc741d0daf385bdaad6c1b09e21a97b0d1fd246f7c7126253073429ead91c0ade0b1cdb24ca9787e000f151e2729fc73017e1",
          "sha256": "9b272e46656fe3a8b0fb8451d2873acf8736e0a0811a99be62a558773cc2bfc2",
          "sha1": "0884c8548bea557a6f7a2c323b4ccc21a8d813f5",
          "md5": "2fe49b2ed412d40e7b09d18f56ffa1ab"
        }
      ]
    }
  ]
}
