{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 19798,
          "sha512": "9f9d5b0b539f04465205470984792d95fc82e149d4fb7db9e9559312478a06cd8fd3992be5b7eb57a33a3f7fe5cde908a052cf7e1a8cd109fce0e3f199b1c543",
          "sha256": "32429db3a618ec8a70e122da6885a262bd4c44382287f5154407a6a643828565",
          "sha1": "281d199b2e036a799a743cb6cca0b4412a4d776b",
          "md5": "4b53420a9ee66702fde31152ee98450c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 19798,
          "sha512": "9f9d5b0b539f04465205470984792d95fc82e149d4fb7db9e9559312478a06cd8fd3992be5b7eb57a33a3f7fe5cde908a052cf7e1a8cd109fce0e3f199b1c543",
          "sha256": "32429db3a618ec8a70e122da6885a262bd4c44382287f5154407a6a643828565",
          "sha1": "281d199b2e036a799a743cb6cca0b4412a4d776b",
          "md5": "4b53420a9ee66702fde31152ee98450c"
        }
      ]
    }
  ]
}
