{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 24443,
          "sha512": "7fab1beac75e04ac27370f852e2f6dab05ee3ad2796ac3dab9e53a94ae43a8e69a424786bdd1dc8a84215708f7195d1a5e5ec3761612850d241b7e0e3dddfc64",
          "sha256": "979aaee5c44593a8361479eb30511babbab02ca0cf1d16d6a12aca33daf8a7f3",
          "sha1": "7b60b14b2737184d46bfea2e26d8068ae4773f71",
          "md5": "8f1151de8cde07399bd0a98793b973c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 24443,
          "sha512": "7fab1beac75e04ac27370f852e2f6dab05ee3ad2796ac3dab9e53a94ae43a8e69a424786bdd1dc8a84215708f7195d1a5e5ec3761612850d241b7e0e3dddfc64",
          "sha256": "979aaee5c44593a8361479eb30511babbab02ca0cf1d16d6a12aca33daf8a7f3",
          "sha1": "7b60b14b2737184d46bfea2e26d8068ae4773f71",
          "md5": "8f1151de8cde07399bd0a98793b973c7"
        }
      ]
    }
  ]
}
