{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59899,
          "sha512": "411053ceaedd193565a334306a717cddc8e0c82a7a5a575486fde87af4f86c7c7af0ff210d8a97d3db0b2e84dff8e59f12d8a328dda1ba745cf10802219de6bf",
          "sha256": "b7683fcbbb41a81f788ff60ddfe62771d5a43a7eb1a8ccf1da94188a3f549b02",
          "sha1": "9838c891a4acdfcb4ba61e576a6ee68e7d285c17",
          "md5": "fb8abe26750870de7f24e2dae3b41503"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59899,
          "sha512": "411053ceaedd193565a334306a717cddc8e0c82a7a5a575486fde87af4f86c7c7af0ff210d8a97d3db0b2e84dff8e59f12d8a328dda1ba745cf10802219de6bf",
          "sha256": "b7683fcbbb41a81f788ff60ddfe62771d5a43a7eb1a8ccf1da94188a3f549b02",
          "sha1": "9838c891a4acdfcb4ba61e576a6ee68e7d285c17",
          "md5": "fb8abe26750870de7f24e2dae3b41503"
        }
      ]
    }
  ]
}
