{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 72500,
          "sha512": "8834f4e2e4c7111a8044ace49343f72da86a84e58e068c628e9e912732febc08ae902d1d86352d681bda26e5d293989f6a6fe3b64db6ab1419781e14badfc715",
          "sha256": "a6665b4e8cf1ebedddcf3499fe52345b042352bace2c7eb1129275564b76728e",
          "sha1": "2d7c1be133d482ea22e998a462c9adf54050b5be",
          "md5": "d9fa1ad8d360e0d44536658a61366210"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 72500,
          "sha512": "8834f4e2e4c7111a8044ace49343f72da86a84e58e068c628e9e912732febc08ae902d1d86352d681bda26e5d293989f6a6fe3b64db6ab1419781e14badfc715",
          "sha256": "a6665b4e8cf1ebedddcf3499fe52345b042352bace2c7eb1129275564b76728e",
          "sha1": "2d7c1be133d482ea22e998a462c9adf54050b5be",
          "md5": "d9fa1ad8d360e0d44536658a61366210"
        }
      ]
    }
  ]
}
