{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 13408,
          "sha512": "5ed72e77d432135d0513e71263ff13765a1ac1b0ef484e7f9b7c48fa631fd82edabcb5345e165e070871523805c9e1ef8aa3aa2738295503f79bea97671a27c1",
          "sha256": "cc75bffcf7365c2a1bbd87b187da91e82e938d86d87b07043e0a55a285666a89",
          "sha1": "46da5aa27e70ecd5527d29eecd280ae208978e87",
          "md5": "07460ad20fe38031bc5efe4f09ace7e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 13408,
          "sha512": "5ed72e77d432135d0513e71263ff13765a1ac1b0ef484e7f9b7c48fa631fd82edabcb5345e165e070871523805c9e1ef8aa3aa2738295503f79bea97671a27c1",
          "sha256": "cc75bffcf7365c2a1bbd87b187da91e82e938d86d87b07043e0a55a285666a89",
          "sha1": "46da5aa27e70ecd5527d29eecd280ae208978e87",
          "md5": "07460ad20fe38031bc5efe4f09ace7e6"
        }
      ]
    }
  ]
}
