{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65818,
          "sha512": "5a381f98627387e587d834a9623ad1181a89956beb957f2dfe2d32892dd7578b80f6f3a6f3a77261544c2e9c6fc45861930570ca60856847818c0a8a08f4e359",
          "sha256": "949e304abafdd822ef13c18c702c1808a462ca3e5d25fd2eb99541a008ada97e",
          "sha1": "d0268df48c91a5c758b136e674c05ff5f62babec",
          "md5": "e9af9d7915e709b71090e1e46037b6c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 65818,
          "sha512": "5a381f98627387e587d834a9623ad1181a89956beb957f2dfe2d32892dd7578b80f6f3a6f3a77261544c2e9c6fc45861930570ca60856847818c0a8a08f4e359",
          "sha256": "949e304abafdd822ef13c18c702c1808a462ca3e5d25fd2eb99541a008ada97e",
          "sha1": "d0268df48c91a5c758b136e674c05ff5f62babec",
          "md5": "e9af9d7915e709b71090e1e46037b6c3"
        }
      ]
    }
  ]
}
