{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 12843,
          "sha512": "278e9de5d11e0f61fb4bf54266a73939353184e2a9fd94b2320ad529159350caba64acfdc3d68c91b453eb85ee7ccb84516805730fa21a4e71a7d34daedee05f",
          "sha256": "356771ad3df5f7d1c7641fb5a3c641cc4fb7d6835d93bdf7eddad70b48b1a78c",
          "sha1": "e434d40bd2a3e96d3f27734e2e95cb1e6f825ad6",
          "md5": "b7453df2fc386af7191c4b7b63ee0ad2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 12843,
          "sha512": "278e9de5d11e0f61fb4bf54266a73939353184e2a9fd94b2320ad529159350caba64acfdc3d68c91b453eb85ee7ccb84516805730fa21a4e71a7d34daedee05f",
          "sha256": "356771ad3df5f7d1c7641fb5a3c641cc4fb7d6835d93bdf7eddad70b48b1a78c",
          "sha1": "e434d40bd2a3e96d3f27734e2e95cb1e6f825ad6",
          "md5": "b7453df2fc386af7191c4b7b63ee0ad2"
        }
      ]
    }
  ]
}
