{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56516,
          "sha512": "0e019e1e4aa1139ba7d08ca2870434478221d85e3cd6ed2a8f0e481fb9112cc87ef4be0147f0abe49d27bfd28d2f8b8c734be7a033be13695c923953c44a756d",
          "sha256": "a5d37284947725c0b63a2dfc2f9faa0c0e5b7aff3a057134bb2200d4f3069514",
          "sha1": "7123e4a5b9e83d981d8d88af3a3bfb152d25520a",
          "md5": "d6fc07e2a843cd315314f7256a32c004"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56516,
          "sha512": "0e019e1e4aa1139ba7d08ca2870434478221d85e3cd6ed2a8f0e481fb9112cc87ef4be0147f0abe49d27bfd28d2f8b8c734be7a033be13695c923953c44a756d",
          "sha256": "a5d37284947725c0b63a2dfc2f9faa0c0e5b7aff3a057134bb2200d4f3069514",
          "sha1": "7123e4a5b9e83d981d8d88af3a3bfb152d25520a",
          "md5": "d6fc07e2a843cd315314f7256a32c004"
        }
      ]
    }
  ]
}
