{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53780,
          "sha512": "28b8d3bb996aa701abf65e1513a4ba41fcb37137d8923302db169457dd94694c2e338b135dd93daa4c150c2c8526199de3e3e32368a17cd6d27001df4ea79ce1",
          "sha256": "1569455615c57cefc10de50a6bb7a448d1ab5ce47037576b3044106e4c02047a",
          "sha1": "9985d020047bc87983c4175eeeed8307d22d4567",
          "md5": "77de3b45363a251c77356c363b25772a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 53780,
          "sha512": "28b8d3bb996aa701abf65e1513a4ba41fcb37137d8923302db169457dd94694c2e338b135dd93daa4c150c2c8526199de3e3e32368a17cd6d27001df4ea79ce1",
          "sha256": "1569455615c57cefc10de50a6bb7a448d1ab5ce47037576b3044106e4c02047a",
          "sha1": "9985d020047bc87983c4175eeeed8307d22d4567",
          "md5": "77de3b45363a251c77356c363b25772a"
        }
      ]
    }
  ]
}
