{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 74350,
          "sha512": "4ff37e34d68feec8057f39605daba89c34a3c02a880cd13fa385004e06f3f7eb248701096ee69b3a204e4485f006b3cedf74e6485a923047868855ba16746862",
          "sha256": "8b9776440c2857cf163b2edecb5aa38faeece75d4d3f170874b070d2f0855242",
          "sha1": "d76414c52092ca8353f1786475664f495b3b5edb",
          "md5": "d18988f0406d1f29f4e7b9f168c67cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 74350,
          "sha512": "4ff37e34d68feec8057f39605daba89c34a3c02a880cd13fa385004e06f3f7eb248701096ee69b3a204e4485f006b3cedf74e6485a923047868855ba16746862",
          "sha256": "8b9776440c2857cf163b2edecb5aa38faeece75d4d3f170874b070d2f0855242",
          "sha1": "d76414c52092ca8353f1786475664f495b3b5edb",
          "md5": "d18988f0406d1f29f4e7b9f168c67cf3"
        }
      ]
    }
  ]
}
