{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 20081,
          "sha512": "52f418777ad4e3dfeca6b354f9c3b504a9ea9b5d90fde882ace172cc4ac81d9941d00a567f1dbef39e983d7f457a4eafbc95017a925be771bb9ddf7c2e7329e1",
          "sha256": "8574e8d0439703bd6b246bdff5f3c90c9a7b23a8e3e74b9f489f746a10b7f336",
          "sha1": "958ca6c93dcc66611536644a7fb7cb413f2147d1",
          "md5": "44aaff3acf9542dea241f3efe14c8d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 20081,
          "sha512": "52f418777ad4e3dfeca6b354f9c3b504a9ea9b5d90fde882ace172cc4ac81d9941d00a567f1dbef39e983d7f457a4eafbc95017a925be771bb9ddf7c2e7329e1",
          "sha256": "8574e8d0439703bd6b246bdff5f3c90c9a7b23a8e3e74b9f489f746a10b7f336",
          "sha1": "958ca6c93dcc66611536644a7fb7cb413f2147d1",
          "md5": "44aaff3acf9542dea241f3efe14c8d9c"
        }
      ]
    }
  ]
}
