{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56845,
          "sha512": "ba9a855dff7298c6d53e716c02e58d1b4009bc2f1aa51e75ce71d998836c89ba1155863ca3e6e5f2e259ddd32e2735e4099cad5033d58fbf224e723ec2bdb7f8",
          "sha256": "5b96a3d782d8fd9b39c88f503ed81b2ed0cae0319863bc1f5640d48a0e0ed00a",
          "sha1": "a1f6573567bdcaa375b3a912cf2c14faf8e23cb1",
          "md5": "9fb14370eb70eb26cf82a8cd95cdb0ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56845,
          "sha512": "ba9a855dff7298c6d53e716c02e58d1b4009bc2f1aa51e75ce71d998836c89ba1155863ca3e6e5f2e259ddd32e2735e4099cad5033d58fbf224e723ec2bdb7f8",
          "sha256": "5b96a3d782d8fd9b39c88f503ed81b2ed0cae0319863bc1f5640d48a0e0ed00a",
          "sha1": "a1f6573567bdcaa375b3a912cf2c14faf8e23cb1",
          "md5": "9fb14370eb70eb26cf82a8cd95cdb0ce"
        }
      ]
    }
  ]
}
