{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 27495,
          "sha512": "1d78c20c7c6350bff1d5f9263b439decb888fda288d1dd8c5e7337cad26c222523cec85367b5b6ef29b6fd6cf5c8746fe6f84475edde8fdd41394c10ad30fc80",
          "sha256": "85b446f768f1b09a5976783196b0e2f182da3a0ae9fb80991f4df91be0cae86e",
          "sha1": "f3c02f9a378b7d06b25bd361387bc2c820af42d9",
          "md5": "85ceeaacb06c862bad8f29be6619a0bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 27495,
          "sha512": "1d78c20c7c6350bff1d5f9263b439decb888fda288d1dd8c5e7337cad26c222523cec85367b5b6ef29b6fd6cf5c8746fe6f84475edde8fdd41394c10ad30fc80",
          "sha256": "85b446f768f1b09a5976783196b0e2f182da3a0ae9fb80991f4df91be0cae86e",
          "sha1": "f3c02f9a378b7d06b25bd361387bc2c820af42d9",
          "md5": "85ceeaacb06c862bad8f29be6619a0bc"
        }
      ]
    }
  ]
}
