{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61413,
          "sha512": "a10552de245a8688ba8e57913c6fc57ee28e00bb51a57819411977d2e738ad3f9debbd836e02febc7a4d0f72ffc0c188acb40fba396f18ece0988d0053a7a6b3",
          "sha256": "bf7235ef0adfaf631d73948f16bffb6db37d8c9af690657b74644127267c8366",
          "sha1": "a4f1588e9fecfbb96962608c55daa84ab0728aa3",
          "md5": "320af580ae6fa3e15dce34bb4fa6d26e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 61413,
          "sha512": "a10552de245a8688ba8e57913c6fc57ee28e00bb51a57819411977d2e738ad3f9debbd836e02febc7a4d0f72ffc0c188acb40fba396f18ece0988d0053a7a6b3",
          "sha256": "bf7235ef0adfaf631d73948f16bffb6db37d8c9af690657b74644127267c8366",
          "sha1": "a4f1588e9fecfbb96962608c55daa84ab0728aa3",
          "md5": "320af580ae6fa3e15dce34bb4fa6d26e"
        }
      ]
    }
  ]
}
