{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 22105,
          "sha512": "da97a6052d178076c579dbca16922ddb3e361649077c2ba49ae0b3d0868e219b0651cfad654ed764569126791fa16d236ede496f1010a52de25b66d9fb8610cd",
          "sha256": "6d5b020e04edff3218320c530cb398136736694b2066b84edda6cdb95381cdb3",
          "sha1": "cbcb599188438016965acbf87ba889f8720fbdb8",
          "md5": "5847681bb1ab4208a128f512a70ef67a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 22105,
          "sha512": "da97a6052d178076c579dbca16922ddb3e361649077c2ba49ae0b3d0868e219b0651cfad654ed764569126791fa16d236ede496f1010a52de25b66d9fb8610cd",
          "sha256": "6d5b020e04edff3218320c530cb398136736694b2066b84edda6cdb95381cdb3",
          "sha1": "cbcb599188438016965acbf87ba889f8720fbdb8",
          "md5": "5847681bb1ab4208a128f512a70ef67a"
        }
      ]
    }
  ]
}
