{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59937,
          "sha512": "04bea9930c3df0c226f171da3ace817b559c758cd3bd1fbb9d4dfb10d93519058799ff3f5f84e5f3d5e89e3e9e25226847fccbdf8ad05aacf71a959400c6a7ab",
          "sha256": "e3737170fa3c8c3d52ddfabbf110005d0fd84d89abfe65135219862d3f613786",
          "sha1": "e27ad6efc9b0ae06d626066a0bab1c0859250b51",
          "md5": "6cc30fae39144318bde7d569fbc0777e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 59937,
          "sha512": "04bea9930c3df0c226f171da3ace817b559c758cd3bd1fbb9d4dfb10d93519058799ff3f5f84e5f3d5e89e3e9e25226847fccbdf8ad05aacf71a959400c6a7ab",
          "sha256": "e3737170fa3c8c3d52ddfabbf110005d0fd84d89abfe65135219862d3f613786",
          "sha1": "e27ad6efc9b0ae06d626066a0bab1c0859250b51",
          "md5": "6cc30fae39144318bde7d569fbc0777e"
        }
      ]
    }
  ]
}
