{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25487,
          "sha512": "821c32f5261c73f3800b4919b334d60d5bbf955a2bc60cc567e818b70e91d53700d43de4bf40f041a9502c0522c45c7909f5852d8149a189a7fc6e27510feea3",
          "sha256": "e070c3a55ba7ca12b835350dc2a059869b67c134b9fa88521a224889784bdf34",
          "sha1": "65378569ee9ba668d1f9f0e984ef423d6589e3f1",
          "md5": "ffddd412522f8a36093dad84e8dcee40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 25487,
          "sha512": "821c32f5261c73f3800b4919b334d60d5bbf955a2bc60cc567e818b70e91d53700d43de4bf40f041a9502c0522c45c7909f5852d8149a189a7fc6e27510feea3",
          "sha256": "e070c3a55ba7ca12b835350dc2a059869b67c134b9fa88521a224889784bdf34",
          "sha1": "65378569ee9ba668d1f9f0e984ef423d6589e3f1",
          "md5": "ffddd412522f8a36093dad84e8dcee40"
        }
      ]
    }
  ]
}
