{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64747,
          "sha512": "176514cbfcab074083669e5774bf21773a0781b1ad97573c4b1b8ad17c3aa81cfe507ba4384f7aea96ff6387e6598abe78508aea7c899e8867567ed56b0e6eec",
          "sha256": "faf31316ed1cd8be1b2fcf03fb707c29cb6c731a99616fc0061cacbd8c586348",
          "sha1": "a941fc68cba87077ef68297ddb0797587f716bf7",
          "md5": "66bb94067120e1f1e5b46e6216b75da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64747,
          "sha512": "176514cbfcab074083669e5774bf21773a0781b1ad97573c4b1b8ad17c3aa81cfe507ba4384f7aea96ff6387e6598abe78508aea7c899e8867567ed56b0e6eec",
          "sha256": "faf31316ed1cd8be1b2fcf03fb707c29cb6c731a99616fc0061cacbd8c586348",
          "sha1": "a941fc68cba87077ef68297ddb0797587f716bf7",
          "md5": "66bb94067120e1f1e5b46e6216b75da0"
        }
      ]
    }
  ]
}
