{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55218,
          "sha512": "e8815a17e58ddc902881fc441e3481d1ec50318460b2eaaf93bfaffc5ca78da4d31279b1eef0082cf4abb214eac8d63482a3720c796ad05aea80ec89591b4466",
          "sha256": "bb46de22c96a95145353adc8935af98071e758248b4a022e32e66879af6a7115",
          "sha1": "00c22a7a7d9512459716d3637cea50bfc9dbd409",
          "md5": "b01c87a13a2fb2cf47124064b2bb0288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55218,
          "sha512": "e8815a17e58ddc902881fc441e3481d1ec50318460b2eaaf93bfaffc5ca78da4d31279b1eef0082cf4abb214eac8d63482a3720c796ad05aea80ec89591b4466",
          "sha256": "bb46de22c96a95145353adc8935af98071e758248b4a022e32e66879af6a7115",
          "sha1": "00c22a7a7d9512459716d3637cea50bfc9dbd409",
          "md5": "b01c87a13a2fb2cf47124064b2bb0288"
        }
      ]
    }
  ]
}
