{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 24588,
          "sha512": "3b20d35726540cb973c45c199697242c7589a4218b4b5900f3d1c2a89d59c331b007d20ca21eb2ecbc0b454de7a3e4b83976dd926d74757a98feaf7b845c20c5",
          "sha256": "dd8689a6303aaa996e9919ba7da3bf49dad2d3eb9496327796ecdb2a74634abc",
          "sha1": "9a8643d972ac814c023d788b5e6b8ab88a645096",
          "md5": "3da01ace1d6993408e17ae3a91c4abf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 24588,
          "sha512": "3b20d35726540cb973c45c199697242c7589a4218b4b5900f3d1c2a89d59c331b007d20ca21eb2ecbc0b454de7a3e4b83976dd926d74757a98feaf7b845c20c5",
          "sha256": "dd8689a6303aaa996e9919ba7da3bf49dad2d3eb9496327796ecdb2a74634abc",
          "sha1": "9a8643d972ac814c023d788b5e6b8ab88a645096",
          "md5": "3da01ace1d6993408e17ae3a91c4abf1"
        }
      ]
    }
  ]
}
