{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56696,
          "sha512": "2ed309a0f94995d03af03516760d2d930511a1ac23e7174bcb3433475550549ef3b04bb44120cf865083c3c3865ece9e6fdf76b7f2d415ae88c509dfa514a096",
          "sha256": "ba80e1dfb4854e80740666491d081a953ad190d5fcff362b913fb1141c467fc1",
          "sha1": "e5551e909edbe251fefa1c9b104bd27e7c21e678",
          "md5": "966883b443bf603ce9a03090d460ed0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56696,
          "sha512": "2ed309a0f94995d03af03516760d2d930511a1ac23e7174bcb3433475550549ef3b04bb44120cf865083c3c3865ece9e6fdf76b7f2d415ae88c509dfa514a096",
          "sha256": "ba80e1dfb4854e80740666491d081a953ad190d5fcff362b913fb1141c467fc1",
          "sha1": "e5551e909edbe251fefa1c9b104bd27e7c21e678",
          "md5": "966883b443bf603ce9a03090d460ed0e"
        }
      ]
    }
  ]
}
