{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55907,
          "sha512": "a95eb9a791d9d671f398eb2ce6817dbe1afa71829ad43553842597c02abc99ac11295723f314cffee369b248e77b307e7fedcae2690a3430e3c79f61718e1db8",
          "sha256": "931af7fb66a401c877e48ecb5796cb9a3e58f70f902d70a8214901f45f850698",
          "sha1": "643a7c0eb458c0e54a746def63dd38d13566504b",
          "md5": "90e6580651e98bf49a0dd7f1bdf38724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55907,
          "sha512": "a95eb9a791d9d671f398eb2ce6817dbe1afa71829ad43553842597c02abc99ac11295723f314cffee369b248e77b307e7fedcae2690a3430e3c79f61718e1db8",
          "sha256": "931af7fb66a401c877e48ecb5796cb9a3e58f70f902d70a8214901f45f850698",
          "sha1": "643a7c0eb458c0e54a746def63dd38d13566504b",
          "md5": "90e6580651e98bf49a0dd7f1bdf38724"
        }
      ]
    }
  ]
}
