{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55188,
          "sha512": "21428ec9890e524a9e959b41e6581e1642300a304a9b02af443850f74520d52622a30a2a3482e78ed58371d89a3dea96f6635366f312439cf7b807bd032055ec",
          "sha256": "d5219d37102aa5be74473bf2997f1c84d761e30a8dde2268d589a61e6bc33fc3",
          "sha1": "1c806cceaf8422fe4b4a13632dcae1b1c5b12c04",
          "md5": "66bd46740226c879a1b30b5ea9e7211c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 55188,
          "sha512": "21428ec9890e524a9e959b41e6581e1642300a304a9b02af443850f74520d52622a30a2a3482e78ed58371d89a3dea96f6635366f312439cf7b807bd032055ec",
          "sha256": "d5219d37102aa5be74473bf2997f1c84d761e30a8dde2268d589a61e6bc33fc3",
          "sha1": "1c806cceaf8422fe4b4a13632dcae1b1c5b12c04",
          "md5": "66bd46740226c879a1b30b5ea9e7211c"
        }
      ]
    }
  ]
}
