{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56323,
          "sha512": "a6de32d0e5e15e7e6f7299fabbd73b12a0af73a62864baf258645419357feb6973798ca235d0b2c265bc3e8946e6ac0371d755adeb13311c181b8d24df23879d",
          "sha256": "229bc1e1380dfa90c44731a7fc075a2494e5a5c756299380c05541b88fb700c2",
          "sha1": "e01dbea84f769652c3d0b747af3f959aebb397bb",
          "md5": "826a8def9ebe9861685e542a1c573978"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 56323,
          "sha512": "a6de32d0e5e15e7e6f7299fabbd73b12a0af73a62864baf258645419357feb6973798ca235d0b2c265bc3e8946e6ac0371d755adeb13311c181b8d24df23879d",
          "sha256": "229bc1e1380dfa90c44731a7fc075a2494e5a5c756299380c05541b88fb700c2",
          "sha1": "e01dbea84f769652c3d0b747af3f959aebb397bb",
          "md5": "826a8def9ebe9861685e542a1c573978"
        }
      ]
    }
  ]
}
