{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hele.plugin",
    "module": "template",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64996,
          "sha512": "605b49e7a1dece460c94c0642d25bc3e3fc85caab5b9c20942c3efed6d81b4adc8119cda0c1df1af72648e44ee7c2b828953f7ce89ea2fcddcba393b05aa7286",
          "sha256": "3d2138e58391a36cf9686fa0493f2085537d02a6d75622337aaa01856edc3abc",
          "sha1": "b8924f91786dd3eb70b75f65cd99db29c77f38c1",
          "md5": "a33544fdbac8f560df2ca4ff2f93ecfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0-SNAPSHOT.jar",
          "url": "template-1.0.0-SNAPSHOT.jar",
          "size": 64996,
          "sha512": "605b49e7a1dece460c94c0642d25bc3e3fc85caab5b9c20942c3efed6d81b4adc8119cda0c1df1af72648e44ee7c2b828953f7ce89ea2fcddcba393b05aa7286",
          "sha256": "3d2138e58391a36cf9686fa0493f2085537d02a6d75622337aaa01856edc3abc",
          "sha1": "b8924f91786dd3eb70b75f65cd99db29c77f38c1",
          "md5": "a33544fdbac8f560df2ca4ff2f93ecfe"
        }
      ]
    }
  ]
}
