name: Android CI

on:
  push:
    branches:
      - main
      - 'release/**'
      - 'debug/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
        type: string
      mode:
        description: 'Build mode (debug or release)'
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Verify Directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    - name: Build with Gradle
      run: ./gradlew assemble${{ github.event.inputs.mode }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-${{ github.event.inputs.mode }}
        path: app/build/outputs/apk/${{ github.event.inputs.mode }}/*.apk

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data \
        '{"text":"Build for branch ${{ github.event.inputs.branch }} in ${{ github.event.inputs.mode }} mode is complete."}' \
        $SLACK_WEBHOOK_URL
